### ISSUE TITLE
Fix pep8 violations according to new 1.6.0 version

### ISSUE THREAD

**Issue by Nurdok** [GreenSteam/pep257#102]
There was a new release of pep8 yesterday (Feb 6th, 2015) that added some new checks that pep257 violates (most notably lambda expression assignment). We need to fix these violations for our build to pass.

**Comment by sigmavirus24** [comment]
@Nurdok mind if I take a crack at them?

**Comment by Nurdok** [comment]
I would absolutely love it if you do.
