### ISSUE TITLE
Add an error code for missing docstring in a package

### ISSUE THREAD

**Issue by Nurdok** [GreenSteam/pep257#106]
Missing docstring in `__init__.py` files should be a different error than in a regular module.

**Comment by sigmavirus24** [comment]
Is it so this can be ignored more easily?

**Comment by Nurdok** [comment]
Yes. I find that docstring in (mostly empty) `__init__.py` files are usually ignored, as opposed to regular models.

**Comment by jayvdb** [comment]
If this is done, I suggest it should only a different code if the __init__.py is effectively empty, and preferably **without** imports.  But in that case, why not just exclude the __init__.py entirely?

**Comment by sigmavirus24** [comment]
@jayvdb No one is arguing that this should be off by default but that it should just be an entirely separate error.

**Comment by jayvdb** [comment]
I didnt mention 'default'.

I am suggesting it isnt a separate problem deserving of a separate error code unless the contents of the file are somehow different.  a/foo/__init__.py is not substantially different from a/foo.py unless a/foo/bar.py exists.
