### ISSUE TITLE
D302 and unicode_literals

### ISSUE THREAD

**Issue by max-arnold** [GreenSteam/pep257#113]
If a file contains the following header

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
```

pep257 tool still warns `D302  Use u""" for docstrings with Unicode` on unicode docstrings. Maybe I'm missing something, but this is probably a bug.

**Comment by keleshev** [comment]
Yes, thanks for reporting.

**Comment by max-arnold** [comment]
Do you have any estimation for this bug to be fixed?

**Comment by Nurdok** [comment]
@max-arnold Not yet, no.

**Comment by Nurdok** [comment]
Done! I would love it if you could try it out and give some feedback.
Thanks!

**Comment by max-arnold** [comment]
Works as expected, thanks a lot guys! Any plans for the next release?

**Comment by Nurdok** [comment]
I have plans, but then there's reality... :)
I hope to release a new version in a couple of weeks.
