### ISSUE TITLE
Are D203 and D211 in conflict?

### ISSUE THREAD

**Issue by jacebrowning** [GreenSteam/pep257#141]
From http://pep257.readthedocs.org/en/latest/error_codes.html:

> D203: 1 blank line required before class docstring

> D211: No blank lines allowed before class docstring

It seems impossible to satisfy both as this fails `D211`:

```
class Class:

    """A sample class."""
```

and this fails `D203`:

```
class Class:
    """A sample class."""
```

What am I missing?

**Comment by jacebrowning** [comment]
I tend to just disable `D203` in my projects.

**Comment by Nurdok** [comment]
Yes, they are in conflict. D203 should be disabled by default. See #91.

**Comment by jacebrowning** [comment]
Its seems to be enabled in `0.7.0`:

```
$ cat demo/sample.py
"""A sample module."""


class Class(object):
    """A sample class."""

$ pep257 --version
0.7.0

$ pep257 demo
demo/sample.py:4 in public class `Class`:
        D203: 1 blank line required before class docstring (found 0)

```

**Comment by Nurdok** [comment]
Do you have a configuration file with an `ignore` option in the same directory? I just checked 0.7.0 in a virtualenv and it behaves as expected.

**Comment by jacebrowning** [comment]
Yes:

```
[pep257]

ignore = D202
```
Is the presence of an `ignore` option going to enable normally disabled rules?

**Comment by Nurdok** [comment]
Yes. If you want to add your `ignore` to the list instead of overriding it, use `add-ignore` in the config file (or `--add-ignore` in the command line).

**Comment by jacebrowning** [comment]
Thanks!
