### ISSUE TITLE
D211 Question

### ISSUE THREAD

**Issue by rmk135** [GreenSteam/pep257#144]
Hey there,

I use this tool for my project https://github.com/rmk135/dependency_injector for some time and I was really surprised with 0.7.0 version. I'm talking about adding check D211... I found some mentions about update of PEP257 according to this rule, but I used to find any other mentions of this update and found nothing :( Can you please point me somewhere or help me to get understanding of the full scope of PEP257 update?

**Comment by Nurdok** [comment]
The full release notes are over at our documentation: http://pep257.readthedocs.org/en/latest/release_notes.html#october-9th-2015

Regarding D211, see #137. PEP257 was only updated with this specific change, as far as I know, and you can find the commit message here: https://hg.python.org/peps/rev/9b715d8246db

**Comment by rmk135** [comment]
Yeah, I see! Thanks for a quick response :+1:
