### ISSUE TITLE
Add trim() function from pep257 text

### ISSUE THREAD

**Issue by vrusinov** [GreenSteam/pep257#149]
https://www.python.org/dev/peps/pep-0257/ contains sample code for sometimes useful trim() function.

```python
def trim(docstring):
    if not docstring:
        return ''
    # Convert tabs to spaces (following the normal Python rules)
    # and split into a list of lines:
    lines = docstring.expandtabs().splitlines()
    # Determine minimum indentation (first line doesn't count):
    indent = sys.maxint
    for line in lines[1:]:
        stripped = line.lstrip()
        if stripped:
            indent = min(indent, len(line) - len(stripped))
    # Remove indentation (first line is special):
    trimmed = [lines[0].strip()]
    if indent < sys.maxint:
        for line in lines[1:]:
            trimmed.append(line[indent:].rstrip())
    # Strip off trailing and leading blank lines:
    while trimmed and not trimmed[-1]:
        trimmed.pop()
    while trimmed and not trimmed[0]:
        trimmed.pop(0)
    # Return a single string:
    return '\n'.join(trimmed)
```

I don't want to carry copies of it around, I'd like to depend on something from my project.

Your project seems to be a perfect place to carry this code (I understand purpose is different but name is perfect).
What do you think about adding it here?

Note that pep and this code is in public domain, so it does not looks like there's going to be any license collision.

**Comment by sigmavirus24** [comment]
This could just as easily be a stand-alone package on PyPI

**Comment by Nurdok** [comment]
I agree with @sigmavirus24. "The name is perfect"  is not really a good reason to carry the extra code :)
