### ISSUE TITLE
The first word in a docstring should be capitalized

### ISSUE THREAD

**Issue by Nurdok** [GreenSteam/pep257#164]
This docstring

```.py
def foo():
    """return x."""
```
Should return an error in this style:

`D4xx: First sentence of a docstring should be capitalized ("Return", not "return")`

I haven't found a section in the original PEP that refers to capitalization, but all of the examples in the PEP are correctly capitalized. I'm wondering whether this new error should be checked by default. My instinct says that "a phrase ending in a period" (from the PEP) is a proper sentence, which should be capitalized, but I'm not sure if the PEP mandates it.

Does anyone have any thought regarding this?

**Comment by sigmavirus24** [comment]
So PEP 8 authors are typically happy to clarify their intentions. You can implement this while you wait for a response from the PEP 257 authors and then put it in the default ignore list if you'd like.

**Comment by Nurdok** [comment]
I sent them a query and will start working on this. Thanks for the suggestion.

**Comment by sigmavirus24** [comment]
:cake:

**Comment by Nurdok** [comment]
Implemented in #165
