### ISSUE TITLE
Any leading whitespace should probably be forbidden

### ISSUE THREAD

**Issue by keleshev** [GreenSteam/pep257#42]
Not sure, if it is explicitly mentioned anywhere in PEP 257, but seems to be the case.

**Comment by dolph** [comment]
This was implemented as D210 and released in 0.5.0 (March 14th, 2015).

https://github.com/GreenSteam/pep257/pull/95

**Comment by merwok** [comment]
Does the change forbid the example from my previous message?

**Comment by Nurdok** [comment]
@merwok `D210` would allow your example, but `D200` ("One-line docstring should fit on one line with quotes") would not. So, if you want docstrings in the style of your example, you would need to ignore `D200`.

**Comment by merwok** [comment]
Yes, imagine a multi-line docstring for that example.  Thanks for the reply.
