### ISSUE TITLE
pep257 configuration file

### ISSUE THREAD

**Issue by kdeldycke** [GreenSteam/pep257#58]
pep8 has `~/.config/pep8`.
PyLint has `~/.pylintrc`.
Flake8 has `~/.config/flake8`.
Even PyChecker had `~/.pycheckrc`.

Why can't `pep257` have a configuration file ?

**Comment by oryband** [comment]
Great. Could youp lease add documentation for this please? Specifically to the front page of this repo (README.md)

**Comment by sigmavirus24** [comment]
This is a better opportunity to start using readthedocs.org and have real documentation for this project.
