### ISSUE TITLE
No executable on Windows when installing via pip

### ISSUE THREAD

**Issue by FichteFoll** [GreenSteam/pep257#73]
I installed pep257 0.3.2 using pip with `pip install pep257`, but there is noexecutable in my `C:\Python33\Scripts` path.

There is a Python script named `pep257` (no extension) in the folder but Windows does not know run that via console. I had added `.py` to my PATHEXT env long ago which means entering `pep257` into a shell *should* find it (e.g. `subprocess.Popen("pep257", shell=True)`, so I copied the file to another one with that extension. Now my system can find the file but it fails to execute because `import pep257` tries to import this very file and searches for `main` within, which is obviously not there.

Because of that and the shell restriction all other packages bundle an `.exe` that can always be found and pep257 needs one too.

**Comment by myint** [comment]
@sigmavirus24, correct me if I'm wrong, but I think it is `distribute` rather than `distutils` that has been merged into `setuptools`.

**Comment by sigmavirus24** [comment]
@myint correct. Sorry about that. :)

**Comment by bilderbuchi** [comment]
I also just found this bug. Is there a fix on the horizon?

**Comment by robkorv** [comment]
You can use flake8 with flake8-docstrings on Windows.
