### ISSUE TITLE
PyPI page shows raw ReST source

### ISSUE THREAD

**Issue by mgedmin** [GreenSteam/pep257#84]
https://pypi.python.org/pypi/pep257 looks like this:
![ekrano nuotrauka is 2014-12-17 18 35 54](https://cloud.githubusercontent.com/assets/159967/5474637/9092aeb0-861b-11e4-80ea-12a6b97640ff.png)

Typically this happens when PyPI encounters a ReStructuredText syntax error or a feature that is explicitly disabled for PyPI (like non-absolute URLs in links).

Usually I use [restview](https://pypi.python.org/pypi/restview)'s `--pypi-strict` mode to discover the source of the error, but here restview doesn't complain, so I"m baffled.

**Comment by Nurdok** [comment]
I checked the current master branch against `testpypi` and it looks okay, so I guess it was fixed somewhere along the way. I will close the issue after it is confirmed against the real pypi server.

**Comment by sigmavirus24** [comment]
There have been several updates on PyPI recently to fix formatting issues found by users. The changes have been deployed to both testpypi and pypi itself. You should be able to close this now if it works on testpypi.

**Comment by Nurdok** [comment]
Solved as of version 0.4.1
