### ISSUE TITLE
Real docs

### ISSUE THREAD

**Issue by keleshev** [GreenSteam/pep257#88]
To quote @sigmavirus24 from #58:

> This is a better opportunity to start using readthedocs.org and have real documentation for this project.

I just wanted to move this out into it's own issue and to add that I have the domain www.pep257.org for that. I have no preference regarding docs technology, be it github pages with sphinx or readthedocs.org or anything else.

**Comment by sigmavirus24** [comment]
So @readthedocs is what python-requests.org and python-guide.org uses. Essentially it's a little work to have www.pep257.org be entirely provided by readthedocs.org. It also means that on each push the docs could be rebuilt so they're current and up-to-date. `sphinx quickstart` will also help get some docs ready quickly.

**Comment by Nurdok** [comment]
There is now documentation at pep257.readthedocs.org/, you can go check it out.
