### ISSUE TITLE
package not available on pypi for download

### ISSUE THREAD

**Issue by arunpersaud** [GreenSteam/pep257#94]
not sure if this is the right place to report it, but there are no files to download at

https://pypi.python.org/pypi/pep257/0.4.1

whereas older versions are available.

Arun

**Comment by Nurdok** [comment]
This is my bad - will be fixed shortly (first time uploading to PyPI).

**Comment by Nurdok** [comment]
Fixed. Thanks for reporting this @arunpersaud.
